### ISSUE TITLE
Necessary Fixes

### ISSUE THREAD

**Issue by tannermann** [samuelfarrell/dirigible-pickmeup#1]
Hi, I noticed a few issues with your plugin when I tried to use it:

1. Line 15 in DirigiblePickmeup needs to be updated to use the correct path name. Your plugin name must have changed. It needs to be updated to 'dirigible-pickmeup-master/js/dirigible-pickmeup.js'
2. Line 27 of dirigible-pickmeup.js also needs to be updated to use the correct ID for the ship-to-different-address checkbox. It should be `$('#ship-to-different-address').prop('checked', false).hide();`. Notice I also added `.hide()` to hide the checkbox when local pickup is selected. Which means on line 39, I added `$('#ship-to-different-address').show();` when it should be shown again.

**Comment by samuelfarrell** [comment]
Hey Tanner, nice to hear from a fellow Wisconsinsite!

1) When you clone a repo and download straight from github, it will automatically append -master to your folder (assuming that you are downloading the master branch!) 

2) I'm still seeing the WooCommerce checkbox with the ID of #ship-to-different-address-checkbox. We also don't need to hide the checkbox,  because its contained within the .col-2 that we hide in the next line.!

[Screenshot 15 27 51@2x](https://user-images.githubusercontent.com/4390699/99310648-ede1e100-2820-11eb-9c8d-0ceed912a42a.jpg)
